"""Reusable page builder and sample data for the TableWidget demo."""

from __future__ import annotations

from typing import Any

from nicegui import ui

from nicewidgets.table_widget.column_def import ColumnDef
from nicewidgets.table_widget.config import TableWidgetConfig
from nicewidgets.table_widget.table_widget import TableWidget

ROW_ID_FIELD = 'path'


def make_demo_column_defs() -> list[ColumnDef]:
    """Build demo columns with a category and one editable field."""
    return [
        ColumnDef(field='path', headerName='Path'),
        ColumnDef(field='category', headerName='Category'),
        ColumnDef(field='kind', headerName='Kind', extra={'editable': True}),
        ColumnDef(
            field='size_bytes',
            headerName='Size (bytes)',
            extra={'type': 'numericColumn'},
        ),
    ]


def make_demo_rows() -> list[dict[str, Any]]:
    """Build synthetic rows."""
    return [
        {
            'path': '/lab/slide_a.tif',
            'category': 'Microscopy images',
            'kind': 'TIFF',
            'size_bytes': 1_024_000,
        },
        {
            'path': '/lab/slide_b.czi',
            'category': 'Microscopy images',
            'kind': 'CZI',
            'size_bytes': 8_000_000,
        },
        {
            'path': '/lab/slide_c.nd2',
            'category': 'Microscopy images',
            'kind': 'ND2',
            'size_bytes': 6_500_000,
        },
        {
            'path': '/lab/kymograph_a.oir',
            'category': 'Kymographs',
            'kind': 'OIR',
            'size_bytes': 512_000,
        },
        {
            'path': '/lab/kymograph_b.tif',
            'category': 'Kymographs',
            'kind': 'TIFF',
            'size_bytes': 768_000,
        },
        {
            'path': '/lab/summary.csv',
            'category': 'Analysis results',
            'kind': 'CSV',
            'size_bytes': 12_400,
        },
        {
            'path': '/lab/measurements.csv',
            'category': 'Analysis results',
            'kind': 'CSV',
            'size_bytes': 32_800,
        },
    ]


def build_table_demo_page(
    *,
    embedded: bool = False,
    dark_mode: bool = False,
) -> TableWidget:
    """Build the TableWidget demo in the current NiceGUI slot.

    Args:
        embedded: Whether the page is hosted inside another full-height layout.
        dark_mode: Initial AG Grid color scheme.

    Returns:
        Built table widget.
    """
    height_class = 'h-full' if embedded else 'min-h-screen'
    with ui.column().classes(
        f'w-full {height_class} max-w-5xl mx-auto p-4 gap-4'
    ):
        ui.label('TableWidget demo').classes('text-h5')
        ui.label(
            'Rows are grouped by category using AG Grid Enterprise. The Index '
            'column is generated by TableWidget. Right-click for columns/menu; '
            'double-click a Kind cell to edit.'
        )
        ui.label(
            'AG Grid Enterprise requires a host-provided license in production.'
        ).classes('text-caption text-grey-7')
        selected = ui.label('Selected: (none)')
        edited = ui.label('Edited: (none)')

        def on_row_selected(row: dict[str, Any]) -> None:
            selected.text = f'Selected: {row.get(ROW_ID_FIELD, row)!r}'

        def on_cell_edited(
            row_id: str,
            field: str,
            old_value: Any,
            new_value: Any,
            _row: dict[str, Any],
        ) -> None:
            edited.text = (
                f'Edited: row_id={row_id!r} field={field!r} '
                f'{old_value!r} -> {new_value!r}'
            )

        def on_build_context_menu(table: TableWidget) -> None:
            ui.menu_item(
                'Select first row',
                on_click=lambda: table.set_selected_row_ids(
                    ['/lab/slide_a.tif']
                ),
            )
            ui.menu_item('Clear selection', on_click=table.clear_selection)

        table = TableWidget(
            make_demo_column_defs(),
            ROW_ID_FIELD,
            make_demo_rows(),
            on_row_selected=on_row_selected,
            on_cell_edited=on_cell_edited,
            on_build_context_menu=on_build_context_menu,
            config=TableWidgetConfig(
                selection_mode='single',
                enable_keyboard_row_nav=True,
                show_index_column=True,
                row_group_fields=('category',),
                group_default_expanded=1,
                extra_grid_options={
                    'autoGroupColumnDef': {
                        'headerName': 'Category',
                        'minWidth': 220,
                    },
                },
            ),
        )
        with ui.column().classes('w-full').style('height: 420px;'):
            table.build()
        table.set_dark_mode(dark_mode)

        with ui.row().classes('gap-2'):
            ui.button(
                'Select first row',
                on_click=lambda: table.set_selected_row_ids(
                    ['/lab/slide_a.tif']
                ),
            )
            ui.button('Clear selection', on_click=table.clear_selection)

    return table
